### ISSUE TITLE
6.0.1: sphinx warnings

### ISSUE THREAD

**Issue by kloczek** [python-hyper/hyperframe#159]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] installation
/usr/lib/python3.8/site-packages/hyperframe/frame.py:docstring of hyperframe.frame.Frame.parse_frame_header:13: WARNING: Unknown interpreted text role "param".
WARNING: autodoc: failed to import class 'HyperframeError' from module 'hyperframe.exceptions'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hyperframe.exceptions' has no attribute 'HyperframeError'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: HyperframeError

WARNING: autodoc: failed to import class 'InvalidDataError' from module 'hyperframe.exceptions'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'hyperframe.exceptions' has no attribute 'InvalidDataError'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: InvalidDataError

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... hyperframe.1 { installation api } done
build succeeded, 4 warnings.
```

**Comment by Kriechi** [comment]
similar to https://github.com/python-hyper/hpack/issues/268

I suspect an error in your installation or environment. The full instructions on how to generate the docs are wrapped into tox and work in our CI and locally for me:
`tox -e docs` which is equivalent to a `make html` with an already installed hyperframe package.

Can you test that and report back please?

**Comment by kloczek** [comment]
Indeed it was not updated hyperframe. After upgrade to 6.0.1 still I see some issues but it maybe hyperframe issue.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] installation
/usr/lib/python3.8/site-packages/hyperframe/frame.py:docstring of hyperframe.frame.Frame.parse_frame_header:16: WARNING: Unknown interpreted text role "param".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hyperframe.3 { installation api } done
build succeeded, 2 warnings.
```
tox reports the same issue.
```console
[tkloczko@barrel hyperframe-6.0.1]$ tox -e docs
GLOB sdist-make: /home/tkloczko/rpmbuild/BUILD/hyperframe-6.0.1/setup.py
docs create: /home/tkloczko/rpmbuild/BUILD/hyperframe-6.0.1/.tox/docs
docs installdeps: sphinx>=3.5.4,<4
docs inst: /home/tkloczko/rpmbuild/BUILD/hyperframe-6.0.1/.tox/.tmp/package/1/hyperframe-6.0.1.zip
docs installed: alabaster==0.7.12,Babel==2.9.1,certifi==2021.5.30,chardet==4.0.0,docutils==0.16,hyperframe @ file:///home/tkloczko/rpmbuild/BUILD/hyperframe-6.0.1/.tox/.tmp/package/1/hyperframe-6.0.1.zip,idna==2.10,imagesize==1.2.0,Jinja2==3.0.1,MarkupSafe==2.0.1,packaging==20.9,Pygments==2.9.0,pyparsing==2.4.7,pytz==2021.1,requests==2.25.1,snowballstemmer==2.1.0,Sphinx==3.5.4,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,urllib3==1.26.5
docs run-test-pre: PYTHONHASHSEED='2451454782'
docs run-test: commands[0] | make clean
docs run-test: commands[1] | make html
Running Sphinx v3.5.4
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] api
reading sources... [ 66%] index
reading sources... [100%] installation

/home/tkloczko/rpmbuild/BUILD/hyperframe-6.0.1/.tox/docs/lib/python3.8/site-packages/hyperframe/frame.py:docstring of hyperframe.frame.Frame.parse_frame_header:16: WARNING: Unknown interpreted text role "param".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] api
writing output... [ 66%] index
writing output... [100%] installation

generating indices... genindex done
highlighting module code... [ 50%] hyperframe.exceptions
highlighting module code... [100%] hyperframe.frame

writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in build/html.
_________________________________________________________________________________ summary __________________________________________________________________________________
  docs: commands succeeded
  congratulations :)
```
